languageCode = "en-us"
baseurl = "http://www.bradyinc.com/"
copyright = "© 2016 Brady & Associates"
title = "Brady & Associates"
theme = "brady"
[params]
  description = "We use data, systems thinking, and change management techniques to help hospitals improve their organizational effectiveness."
  logo = "img/brady_associates_logo-hospital_benchmark-navy.png"
  logoText = "img/brady_associates-hospital_benchmarking.png"
  keywords = "hospital department staffing benchmarks, hospital department labor benchmarks, hospital department productivity benchmarks, workload-based staffing reviews, organizational design, communities at risk, price transparency, develop new organizational structures, nursing, physician, clinic, productivity solutions, organizational solutions"

[menu.main]
  about = "about-us"

[params.contact]
  email = "info@bradyinc.com"
  address = ["brady & associates",
            "7667 N.W. Prairie View Road, Suite 204",
            "P.O. Box 10508",
            "Kansas City, MO 64188-0508"]
  phone = "816-587-2120"
  fax = "816-587-1698"

[params.contact.form]
  submit = "Submit"

[params.impactdb]
  email = "info@bradyinc.com"

[params.impactdb.form]
  submit = "Submit"
