languageCode = "en-us"
baseurl = "https://www.bradyinc.com/"
copyright = "© 2016 Brady & Associates"
title = "Brady & Associates: Hospital Organizational Specialists"
theme = "brady"
[params]
  description = "We are one of the top healthcare consulting firms that helps to employ benchmarking data, systems thinking and change management techniques to facilitate 360° performance improvement in the clinical setting."
  logo = "img/brady_associates_logo-hospital_benchmark-navy.png"
  logoText = "img/brady_associates-hospital_benchmarking.png"
  keywords = "hospital organization benchmarks, hospital organizational structure, hospital department stafﬁng benchmarks, hospital department labor benchmarks, hospital department productivity benchmarks, workload-based stafﬁng reviews, hospital organizational specialists in Chicago, hospital organizational specialists in St. Louis, hospital organizational specialists in Cleveland, hospital organizational specialists in Atlanta, hospital organizational specialists in Kansas City, Chicago hospital organizational specialists, St. Louis hospital organizational specialists, Cleveland hospital organizational specialists, Atlanta hospital organizational specialists, Kansas City hospital organizational specialists, Chicago hospital consultant, St. Louis hospital consultant, Cleveland hospital consultant, Atlanta hospital consultant, Kansas City hospital consultant, Chicago hospital organization benchmarks, St. Louis hospital organization benchmarks, Cleveland hospital organization benchmarks, Atlanta hospital organization benchmarks, Kansas City hospital organization benchmarks, Chicago hospital consultants, St. Louis hospital consultants, Cleveland hospital consultants, Atlanta hospital consultants, Kansas City hospital consultants"

[params.contact]
  email = "info@bradyinc.com"
  address = ["brady & associates",
            "7667 N.W. Prairie View Road, Suite 204",
            "P.O. Box 10508",
            "Kansas City, MO 64188-0508"]
  phone = "816-587-2120"
  fax = "816-587-1698"

[params.contact.form]
  submit = "Submit"

[params.impactdb]
  email = "info@bradyinc.com"

[params.impactdb.form]
  submit = "Submit"
